// constants/iller.ts
// 01-81 Türkiye il ve plaka listesi.
// AGENT.md: İl/plaka eşlemesi sabit bir veri dosyasında tutulur, kod içine gömülmez.

export interface IlBilgisi {
  plaka: number;
  kod: string; // "01", "02", ... "81"
  isim: string;
}

export const ILLER: readonly IlBilgisi[] = [
  { plaka: 1, kod: '01', isim: 'Adana' },
  { plaka: 2, kod: '02', isim: 'Adıyaman' },
  { plaka: 3, kod: '03', isim: 'Afyonkarahisar' },
  { plaka: 4, kod: '04', isim: 'Ağrı' },
  { plaka: 5, kod: '05', isim: 'Amasya' },
  { plaka: 6, kod: '06', isim: 'Ankara' },
  { plaka: 7, kod: '07', isim: 'Antalya' },
  { plaka: 8, kod: '08', isim: 'Artvin' },
  { plaka: 9, kod: '09', isim: 'Aydın' },
  { plaka: 10, kod: '10', isim: 'Balıkesir' },
  { plaka: 11, kod: '11', isim: 'Bilecik' },
  { plaka: 12, kod: '12', isim: 'Bingöl' },
  { plaka: 13, kod: '13', isim: 'Bitlis' },
  { plaka: 14, kod: '14', isim: 'Bolu' },
  { plaka: 15, kod: '15', isim: 'Burdur' },
  { plaka: 16, kod: '16', isim: 'Bursa' },
  { plaka: 17, kod: '17', isim: 'Çanakkale' },
  { plaka: 18, kod: '18', isim: 'Çankırı' },
  { plaka: 19, kod: '19', isim: 'Çorum' },
  { plaka: 20, kod: '20', isim: 'Denizli' },
  { plaka: 21, kod: '21', isim: 'Diyarbakır' },
  { plaka: 22, kod: '22', isim: 'Edirne' },
  { plaka: 23, kod: '23', isim: 'Elazığ' },
  { plaka: 24, kod: '24', isim: 'Erzincan' },
  { plaka: 25, kod: '25', isim: 'Erzurum' },
  { plaka: 26, kod: '26', isim: 'Eskişehir' },
  { plaka: 27, kod: '27', isim: 'Gaziantep' },
  { plaka: 28, kod: '28', isim: 'Giresun' },
  { plaka: 29, kod: '29', isim: 'Gümüşhane' },
  { plaka: 30, kod: '30', isim: 'Hakkari' },
  { plaka: 31, kod: '31', isim: 'Hatay' },
  { plaka: 32, kod: '32', isim: 'Isparta' },
  { plaka: 33, kod: '33', isim: 'Mersin' },
  { plaka: 34, kod: '34', isim: 'İstanbul' },
  { plaka: 35, kod: '35', isim: 'İzmir' },
  { plaka: 36, kod: '36', isim: 'Kars' },
  { plaka: 37, kod: '37', isim: 'Kastamonu' },
  { plaka: 38, kod: '38', isim: 'Kayseri' },
  { plaka: 39, kod: '39', isim: 'Kırklareli' },
  { plaka: 40, kod: '40', isim: 'Kırşehir' },
  { plaka: 41, kod: '41', isim: 'Kocaeli' },
  { plaka: 42, kod: '42', isim: 'Konya' },
  { plaka: 43, kod: '43', isim: 'Kütahya' },
  { plaka: 44, kod: '44', isim: 'Malatya' },
  { plaka: 45, kod: '45', isim: 'Manisa' },
  { plaka: 46, kod: '46', isim: 'Kahramanmaraş' },
  { plaka: 47, kod: '47', isim: 'Mardin' },
  { plaka: 48, kod: '48', isim: 'Muğla' },
  { plaka: 49, kod: '49', isim: 'Muş' },
  { plaka: 50, kod: '50', isim: 'Nevşehir' },
  { plaka: 51, kod: '51', isim: 'Niğde' },
  { plaka: 52, kod: '52', isim: 'Ordu' },
  { plaka: 53, kod: '53', isim: 'Rize' },
  { plaka: 54, kod: '54', isim: 'Sakarya' },
  { plaka: 55, kod: '55', isim: 'Samsun' },
  { plaka: 56, kod: '56', isim: 'Siirt' },
  { plaka: 57, kod: '57', isim: 'Sinop' },
  { plaka: 58, kod: '58', isim: 'Sivas' },
  { plaka: 59, kod: '59', isim: 'Tekirdağ' },
  { plaka: 60, kod: '60', isim: 'Tokat' },
  { plaka: 61, kod: '61', isim: 'Trabzon' },
  { plaka: 62, kod: '62', isim: 'Tunceli' },
  { plaka: 63, kod: '63', isim: 'Şanlıurfa' },
  { plaka: 64, kod: '64', isim: 'Uşak' },
  { plaka: 65, kod: '65', isim: 'Van' },
  { plaka: 66, kod: '66', isim: 'Yozgat' },
  { plaka: 67, kod: '67', isim: 'Zonguldak' },
  { plaka: 68, kod: '68', isim: 'Aksaray' },
  { plaka: 69, kod: '69', isim: 'Bayburt' },
  { plaka: 70, kod: '70', isim: 'Karaman' },
  { plaka: 71, kod: '71', isim: 'Kırıkkale' },
  { plaka: 72, kod: '72', isim: 'Batman' },
  { plaka: 73, kod: '73', isim: 'Şırnak' },
  { plaka: 74, kod: '74', isim: 'Bartın' },
  { plaka: 75, kod: '75', isim: 'Ardahan' },
  { plaka: 76, kod: '76', isim: 'Iğdır' },
  { plaka: 77, kod: '77', isim: 'Yalova' },
  { plaka: 78, kod: '78', isim: 'Karabük' },
  { plaka: 79, kod: '79', isim: 'Kilis' },
  { plaka: 80, kod: '80', isim: 'Osmaniye' },
  { plaka: 81, kod: '81', isim: 'Düzce' },
] as const;

export function getIlByPlaka(plaka: number): IlBilgisi | undefined {
  if (plaka < 1 || plaka > 81) return undefined;
  return ILLER[plaka - 1];
}
